<!DOCTYPE html>
<html class="unselectable">
    <link rel="shortcut icon" href="ico/m2icon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="css/stil.css">
    <script language="javascript" src="js/rayic.js"></script>
	<script src="js/sweetalert2.min.js"></script>
<link rel="stylesheet" href="css/sweetalert2.min.css">
  <head>
    <meta charset="UTF-8">
    <title>SORGUM²</title></center>
  </head>
<img class="applogo" src="img/Sorgumwht.png" draggable="false"><br>
  <span class="bslk01">KOZAN 2019</span><br>
    <span class="bslk04">"M² BİRİM BEDEL SORGULAMA UYGULAMASI"</span>
  <body style="text-align: center" onload="initListGroup('chainedmenu', document.listmenu0.firstlevel, document.listmenu0.secondlevel, document.listmenu0.thirdlevel, 'savestate')">
    <br><br>
<form name="listmenu0">
<table style="border-spacing: 10px" align="center"><tr><center><td><p>
<td><p><center><span class="bslk02">MAHALLE SEÇİNİZ</span></center></p>
<select class="list" name="firstlevel"></select></td>
<td><p><center><span class="bslk02">CADDE/SOKAK SEÇİNİZ</span></center></p>
&nbsp&nbsp<select class="list" name="secondlevel"></select></td></tr></table>
<br>
<p><center><span class="bslk03">M<sup>2</sup> BİRİM BEDELİ</span></center></p>
<select class="list2" name="thirdlevel"></select>
</form>

       <script>
      // You can also require other files to run in this process
      require('./css/stil.css')
      require('./main.js')
      require('./renderer.js')
      require('./js/rayic.js')
    </script>
      </body>
      <footer>
          <table style="background-color:white; height: 43px; width: 100%;"><tr>  <td valign="top" style="vertical-align: top;" width="43"> <img alt="" width="43" src="img/thr01.png" draggable="false"></td>
          
          <td style="font-size:1em;padding: 0 0 0 5px;vertical-align: top;" valign="top">
          
          <table cellspacing="0" cellpadding="0" border="0" style="width: 100%;max-width: 400px;font-family:'Trebuchet MS', Helvetica, sans-serif;font-size:50%;color: #000001;">
          
          <tr><td style="font-size: 1.5em;color: #000000;font-weight: 600;"> Muhammed Tahir YILMAZ </td></tr>
          
          <tr><td style="padding: 3px 0;font-size: 1.2em;color: #292929;">Grafik Tasarımcı &amp; Programcı</td></tr>
          
          <tr><td><table cellspacing="0" cellpadding="0" border="0"><tr>
          
          <td class="sns"><a href="https://www.facebook.com/mtahiryilmazz" target="_blank"><img class="snslogo" alt="facebook" src="img/fb.png"></a></td>
          
          <td class="sns"><a href="https://twitter.com/mtahiryilmazz" target="_blank"><img class="snslogo" alt="twitter" src="img/twt.png"></a></td>
          
          <td class="sns"><a href="https://plus.google.com/u/1/+mtahiryilmazz" target="_blank"><img class="snslogo" alt="google-plus" src="img/g+.png"></a></td>
          
          <td class="sns"><a href="https://www.linkedin.com/in/mtahiryilmazz/" target="_blank"><img class="snslogo" alt="linkedin" src="img/in.png"></a></td>
          
          <td class="sns"><a href="https://github.com/mtahiryilmazz" target="_blank"><img class="snslogo" alt="github" src="img/git.png"></a></td>
          
          </tr></table></td></tr></table></td></tr></table>
          
          <table class="branding" cellspacing="0" cellpadding="0" border="0"><tr><td style="padding:15px 0 0 0;"></td></tr></table>
          </footer>
		  <script>
// Import the Nucleus Library and init with your app id
const Nucleus = require('electron-nucleus')('5c3996dd818e7500ced59c94')

// Optional: report an event
Nucleus.track('BUTTON_CLICKED')
Nucleus.checkLicense('7b7ff8a4699f2f1d6b2d', (err, license) => {
    if (err) return console.error(err)
    if (license.valid) {
    } else {
let timerInterval
  swal({
  type:'error',
  title: 'Etkinleştirme Başarısız',
  html: 'Uygulama <strong></strong> saniye içinde kapanacaktır.',
  footer: '<b>Etkinleştirme Talebi İçin:05464450443</b>',
  timer: 10000,
  
  onOpen: () => {
      swal.showLoading()
      timerInterval = setInterval(() => {
        swal.getContent().querySelector('strong')
          .textContent = Math.ceil(swal.getTimerLeft() / 1000)
      }, 100)
    },
    onClose: () => {
      clearInterval(timerInterval)
    }
  }).then((result) => {
window.close();
  })
  //app.close();
//dialog.showErrorBox('Hata! Geçerli lisans bulunamadı','Geliştiriciyle iletişime geçerek Lisans alabilirsiniz. Tel5464450443')
   
}
})
</script>
</html>
